name: Chess Stats

on:
  schedule:
    - cron: "0 0 * * *"   # update rating & game terakhir tiap hari
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    name: Update README with chess.com stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Balastrong/chess-stats-action@main
        with:
          CHESS_USERNAME: poggufanz
